---
title: "obj_2"
format: html
editor: visual
---

# Objectif 2

Évaluer l'importance de la phénologie de la turbidité et du niveau d'eau dans la prédiction de la couverture de VAS dans le lac Saint-Pierre, un tronçon particulièrement dynamique.

1.  Estimer la variabilité saisonnière de la turbidité au lac Saint-Pierre via télédétection satellitaire optique.

    1.  Comment la présence de VAS affecte l'estimation de la turbidité?

2.  Dresser un portrait saisonnier de la turbidité, du niveau d'eau et de la température de l'eau pour les années d'observations RSI au lac Saint-Pierre.

3.  Modéliser l'importance des variations spatiotemporelles physico-chimiques du milieu à l'échelle annuelle pour la prédiction de la présence de VAS au lac Saint-Pierre.

Cet objectif est réalisé dans un contexte de collaboration plus large avec l'équipe du Pr. Alexandre Roy (UQTR) et du DEFA (MELCCFP), principalement via l'implication de Jawad Ziyad (Postdoc).

Équipe responsable: Arthur de Grandpré et Jawad Ziyad, avec contribution de Martin Laporte, Charles Martin, Alexandre Roy, Rémy Pouliot, Philippe Brodeur

# Méthodes

# Analyse
